---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[apt::default]
  - name: ubuntu-14.04
    run_list:
      - recipe[apt::default]
  - name: centos-6.5
    run_list:
      - recipe[yum-epel::default]
  - name: centos-5.10
    run_list:
      - recipe[yum-epel::default]

suites:
  - name: default
    run_list:
      - recipe[zeromq-cookbook::default]
    attributes:
      zeromq:
        install_dir: "/usr/local"
  - name: specific_version
    run_list:
      - recipe[zeromq-cookbook::default]
    attributes:
      zeromq:
        src_version: "2.2.0"
        src_checksum: "43904aeb9ea6844f72ca02e4e53bf1d481a1a0264e64979da761464e88604637"
        install_dir: "/usr/local"
        src_mirror: "http://download.zeromq.org/zeromq-2.2.0.tar.gz"

